#!/usr/bin/env python3
"""Embeds design/providers/*.svg into Swift so the app needs no resource bundle.
Run after changing a logo: scripts/embed-logos.py"""
import pathlib, json
root = pathlib.Path(__file__).resolve().parent.parent
ids = {"claude-code": "claude.svg", "codex": "openai.svg", "opencode": "opencode.svg",
       "grok": "grok.svg", "cursor-agent": "cursor.svg"}
lines = ["// Generated by scripts/embed-logos.py from design/providers/. Do not edit.",
         "// Official marks from each vendor's brand kit, shown to identify the provider.", "",
         "enum ProviderLogoData {", "    static let svg: [String: String] = ["]
for harness, name in ids.items():
    svg = (root / "design/providers" / name).read_text().strip()
    lines.append(f"        {json.dumps(harness)}: {json.dumps(svg)},")
lines += ["    ]", "}", ""]
out = root / "Sources/Pollymetric/UI/ProviderLogoData.swift"
out.write_text("\n".join(lines))
print(f"wrote {out.relative_to(root)} ({len(ids)} logos)")
